### PR TITLE
Few updates

### PR DESCRIPTION
**Pull request by Chandlr**
Modified Themida added VMProtect and few installers, FSG .. waiting on Entrypoint bug fix ;)

### CODE REVIEW

**Comment by mrexodia** [comment]
Why did you close it?

**Comment by Chandlr** [comment]
i made more updates since then

**Comment by mrexodia** [comment]
ah okay :)

**Comment by mrexodia** [comment]
Alright, I gave you write access to both this repository and the scripts
repository.

Op vr 11 dec. 2015 om 21:11 schreef Chandlr notifications@github.com:

**Comment by Chandlr** [comment]
cool :)

**Pull request closed without merging**
